/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeUsernameRouteImport } from './routes/analyze.$username'
import { Route as CheckoutUsernameRouteImport } from './routes/checkout.$username'
import { Route as ReportUsernameRouteImport } from './routes/report.$username'
import { Route as ResultUsernameRouteImport } from './routes/result.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeUsernameRoute = AnalyzeUsernameRouteImport.update({
  id: '/analyze/$username',
  path: '/analyze/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutUsernameRoute = CheckoutUsernameRouteImport.update({
  id: '/checkout/$username',
  path: '/checkout/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportUsernameRoute = ReportUsernameRouteImport.update({
  id: '/report/$username',
  path: '/report/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultUsernameRoute = ResultUsernameRouteImport.update({
  id: '/result/$username',
  path: '/result/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/$username': typeof CheckoutUsernameRoute
  '/report/$username': typeof ReportUsernameRoute
  '/result/$username': typeof ResultUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/$username': typeof CheckoutUsernameRoute
  '/report/$username': typeof ReportUsernameRoute
  '/result/$username': typeof ResultUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/$username': typeof CheckoutUsernameRoute
  '/report/$username': typeof ReportUsernameRoute
  '/result/$username': typeof ResultUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze/$username'
    | '/checkout/$username'
    | '/report/$username'
    | '/result/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze/$username'
    | '/checkout/$username'
    | '/report/$username'
    | '/result/$username'
  id:
    | '__root__'
    | '/'
    | '/analyze/$username'
    | '/checkout/$username'
    | '/report/$username'
    | '/result/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeUsernameRoute: typeof AnalyzeUsernameRoute
  CheckoutUsernameRoute: typeof CheckoutUsernameRoute
  ReportUsernameRoute: typeof ReportUsernameRoute
  ResultUsernameRoute: typeof ResultUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$username': {
      id: '/analyze/$username'
      path: '/analyze/$username'
      fullPath: '/analyze/$username'
      preLoaderRoute: typeof AnalyzeUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$username': {
      id: '/checkout/$username'
      path: '/checkout/$username'
      fullPath: '/checkout/$username'
      preLoaderRoute: typeof CheckoutUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$username': {
      id: '/report/$username'
      path: '/report/$username'
      fullPath: '/report/$username'
      preLoaderRoute: typeof ReportUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$username': {
      id: '/result/$username'
      path: '/result/$username'
      fullPath: '/result/$username'
      preLoaderRoute: typeof ResultUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeUsernameRoute: AnalyzeUsernameRoute,
  CheckoutUsernameRoute: CheckoutUsernameRoute,
  ReportUsernameRoute: ReportUsernameRoute,
  ResultUsernameRoute: ResultUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
