/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeUsernameRouteImport } from './routes/analyze.$username'
import { Route as CheckoutAnalysisIdRouteImport } from './routes/checkout.$analysisId'
import { Route as ReportAnalysisIdRouteImport } from './routes/report.$analysisId'
import { Route as ResultAnalysisIdRouteImport } from './routes/result.$analysisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeUsernameRoute = AnalyzeUsernameRouteImport.update({
  id: '/analyze/$username',
  path: '/analyze/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutAnalysisIdRoute = CheckoutAnalysisIdRouteImport.update({
  id: '/checkout/$analysisId',
  path: '/checkout/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAnalysisIdRoute = ReportAnalysisIdRouteImport.update({
  id: '/report/$analysisId',
  path: '/report/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAnalysisIdRoute = ResultAnalysisIdRouteImport.update({
  id: '/result/$analysisId',
  path: '/result/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/$analysisId': typeof CheckoutAnalysisIdRoute
  '/report/$analysisId': typeof ReportAnalysisIdRoute
  '/result/$analysisId': typeof ResultAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/$analysisId': typeof CheckoutAnalysisIdRoute
  '/report/$analysisId': typeof ReportAnalysisIdRoute
  '/result/$analysisId': typeof ResultAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/checkout/$analysisId': typeof CheckoutAnalysisIdRoute
  '/report/$analysisId': typeof ReportAnalysisIdRoute
  '/result/$analysisId': typeof ResultAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze/$username'
    | '/checkout/$analysisId'
    | '/report/$analysisId'
    | '/result/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze/$username'
    | '/checkout/$analysisId'
    | '/report/$analysisId'
    | '/result/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/analyze/$username'
    | '/checkout/$analysisId'
    | '/report/$analysisId'
    | '/result/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeUsernameRoute: typeof AnalyzeUsernameRoute
  CheckoutAnalysisIdRoute: typeof CheckoutAnalysisIdRoute
  ReportAnalysisIdRoute: typeof ReportAnalysisIdRoute
  ResultAnalysisIdRoute: typeof ResultAnalysisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$username': {
      id: '/analyze/$username'
      path: '/analyze/$username'
      fullPath: '/analyze/$username'
      preLoaderRoute: typeof AnalyzeUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$analysisId': {
      id: '/checkout/$analysisId'
      path: '/checkout/$analysisId'
      fullPath: '/checkout/$analysisId'
      preLoaderRoute: typeof CheckoutAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$analysisId': {
      id: '/report/$analysisId'
      path: '/report/$analysisId'
      fullPath: '/report/$analysisId'
      preLoaderRoute: typeof ReportAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$analysisId': {
      id: '/result/$analysisId'
      path: '/result/$analysisId'
      fullPath: '/result/$analysisId'
      preLoaderRoute: typeof ResultAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeUsernameRoute: AnalyzeUsernameRoute,
  CheckoutAnalysisIdRoute: CheckoutAnalysisIdRoute,
  ReportAnalysisIdRoute: ReportAnalysisIdRoute,
  ResultAnalysisIdRoute: ResultAnalysisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
